import { env } from "../config/env.js";
import { OpenAIEmbeddings } from "@langchain/openai";

export interface EmbeddingModel {
  embed(texts: string[]): Promise<number[][]>;
}

export class OpenRouterEmbeddingModel implements EmbeddingModel {
  private readonly model: OpenAIEmbeddings | undefined;
  private readonly fallback = new DeterministicEmbeddingModel();

  constructor() {
    this.model = env.openRouterApiKey
      ? new OpenAIEmbeddings({
          apiKey: env.openRouterApiKey,
          model: env.openRouterEmbeddingModel,
          configuration: {
            baseURL: env.openRouterBaseUrl,
            defaultHeaders: {
              "HTTP-Referer": "http://localhost:5173",
              "X-Title": "Skill Router"
            }
          }
        })
      : undefined;
  }

  async embed(texts: string[]): Promise<number[][]> {
    if (!this.model) {
      console.warn("OpenRouter API key missing, using deterministic fallback for embeddings!");
      return this.fallback.embed(texts);
    }
    try {
      const start = Date.now();
      const result = await this.model.embedDocuments(texts);
      const latency = Date.now() - start;
      console.log(`[Metrics] Embedding generated by OpenRouter in ${latency} ms`);
      return result;
    } catch (e) {
      console.warn("OpenRouter embedding failed, using deterministic fallback!", e);
      return this.fallback.embed(texts);
    }
  }
}

export class BgeSmallEmbeddingModel implements EmbeddingModel {
  private extractorPromise: Promise<unknown> | undefined;
  private readonly fallback = new DeterministicEmbeddingModel();

  constructor(private readonly modelName = env.embeddingModel) {}

  async embed(texts: string[]): Promise<number[][]> {
    try {
      const extractor = await this.getExtractor();
      const pipeline = extractor as (texts: string[], options: { pooling: string; normalize: boolean }) => Promise<{ tolist: () => number[][] }>;
      const start = Date.now();
      const output = await pipeline(texts, { pooling: "mean", normalize: true });
      const result = output.tolist();
      const latency = Date.now() - start;
      console.log(`[Metrics] Embedding generated by BgeSmall in ${latency} ms`);
      return result;
    } catch (e) {
      console.warn("Failed to load Xenova BGE Embedding Model, using Deterministic fallback!", e);
      return this.fallback.embed(texts);
    }
  }

  private async getExtractor(): Promise<unknown> {
    this.extractorPromise ??= import("@xenova/transformers").then(({ pipeline }) =>
      pipeline("feature-extraction", this.modelName)
    );
    return this.extractorPromise;
  }
}

export class DeterministicEmbeddingModel implements EmbeddingModel {
  constructor(private readonly dimensions = 64) {}

  async embed(texts: string[]): Promise<number[][]> {
    return texts.map((text) => {
      const vector = Array.from({ length: this.dimensions }, () => 0);
      for (const token of text.toLowerCase().match(/[a-z0-9]+/g) ?? []) {
        let hash = 0;
        for (const char of token) hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
        vector[hash % this.dimensions] += 1;
      }
      const norm = Math.hypot(...vector) || 1;
      return vector.map((value) => value / norm);
    });
  }
}
